# fly.toml app configuration file generated for kalimba on 2024-01-10T15:05:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kalimba"
primary_region = "yul"

[env]
ENVIRONMENT = "PRODUCTION"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
