name: Fly deploy
on:
  push:
    branches:
      - release

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: deploy to Fly.IO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install typescript
      - run: npm run build 
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
